### ISSUE TITLE
Logo Contest

### ISSUE THREAD

**Issue by RossComputerGuy** [Ross-Technologies/RDE#3]
We need a logo so everyone please submit logos for RDE. Must be a png and 64x64 pixels. Has to include something relating to Node.JS and RDE. The contest will end between a week to a month.

**Comment by David-Phantom** [comment]
![rde_5](https://user-images.githubusercontent.com/44823004/48102915-2f376300-e1fb-11e8-9906-3c2d5d1c9e40.png)

**Comment by David-Phantom** [comment]
![rde_4](https://user-images.githubusercontent.com/44823004/48102917-32caea00-e1fb-11e8-9f43-65ef8d9ce2b0.png)

**Comment by David-Phantom** [comment]
![rde_3](https://user-images.githubusercontent.com/44823004/48102918-352d4400-e1fb-11e8-9a30-fa07c1a3c15a.png)

**Comment by David-Phantom** [comment]
![rde_2](https://user-images.githubusercontent.com/44823004/48102921-378f9e00-e1fb-11e8-9ebf-165d17a1a721.png)

**Comment by David-Phantom** [comment]
![rde](https://user-images.githubusercontent.com/44823004/48102925-39f1f800-e1fb-11e8-9ed7-714502dea500.png)

**Comment by RossComputerGuy** [comment]
Made by Luni#5922 on Discord
![image](https://user-images.githubusercontent.com/19699320/48103181-ec699100-e1e2-11e8-8289-710db9e3d112.png)

**Comment by David-Phantom** [comment]
![rde_6](https://user-images.githubusercontent.com/44823004/48103424-f8624c80-e1fc-11e8-814c-4c372d1d8d4a.png)

**Comment by David-Phantom** [comment]
![rde_d](https://user-images.githubusercontent.com/44823004/48103427-fb5d3d00-e1fc-11e8-892b-9504b9c224fa.png)

**Comment by David-Phantom** [comment]
![rde_9](https://user-images.githubusercontent.com/44823004/48103432-fe582d80-e1fc-11e8-85c7-23fac0f9e6e7.png)

**Comment by David-Phantom** [comment]
![rde_c](https://user-images.githubusercontent.com/44823004/48103436-01ebb480-e1fd-11e8-8003-9cd8ae8382d7.png)

**Comment by David-Phantom** [comment]
![rde_7](https://user-images.githubusercontent.com/44823004/48103440-06b06880-e1fd-11e8-9b51-c606459958b4.png)

**Comment by fire219** [comment]
![image](https://user-images.githubusercontent.com/6289427/48103880-b504df80-e1f6-11e8-974c-87de850880bb.png)

**Comment by RossComputerGuy** [comment]
New logo has been set so the contest has ended.
