### ISSUE TITLE
Wallpaper Contest

### ISSUE THREAD

**Issue by RossComputerGuy** [Ross-Technologies/RDE#4]
Right now the wallpaper by default is a 1920x1080 image of the Wing Gundam. I'd like to have that replaced so please submit a PNG 1920x1080 image that'll go with the design of RDE. The contest will end in a week to a month.

**Comment by fire219** [comment]
![image](https://user-images.githubusercontent.com/6289427/48104897-f8f9e380-e1fa-11e8-9c5b-e6c69d3df7a1.png)

**Comment by fire219** [comment]
brighter version of above: 
![image](https://user-images.githubusercontent.com/6289427/48104942-1464ee80-e1fb-11e8-8c1d-7eb31c78d6c0.png)

**Comment by RossComputerGuy** [comment]
Since no one else is submitting wallpaper, we've closed the contest.
